$
\frac{\partial \mathcal{L}}{\partial Pr(y_{u+1}|t,u)} \\=\\
\frac{\alpha(t,u)\beta(t,u+1)}{Pr(y^*|x)} \\=\\
\frac{\alpha(t,u)\beta(t,u)}{Pr(y^*|x)} \frac{\beta(t,u+1)}{\beta(t,u)} \\=\\
\frac{\alpha(t,u)\beta(t,u)}{Pr(y^*|x )} \big(\frac{\beta(t+1,u)}{\beta(t,u+1)} \empty(t,u) +y_{u+1}(t,u)\big)^{-1}
$

$
\frac{\partial \mathcal{L}}{\partial Pr(\empty|t,u)} =
\frac{\alpha(t,u)\beta(t+1,u)}{Pr(y^*|x)} =
\frac{\alpha(t,u)\beta(t,u)}{Pr(y^*|x)} \big(\empty(t,u) + \frac{\beta(t,u+1)}{\beta(t+1,u)}y(t,u)\big)^{-1}
$

$\beta_n (t,u) \equiv \frac {\beta(t,u)}{\sum_{t,u=t',u'}\beta(t',u')}$

$\frac{\beta(t,u+1)}{\beta(t+1,u)} = \frac{\beta_n(t,u+1)}{\beta_n(t+1,u)}$

$
\frac{\alpha(t,u)\beta(t,u)}{Pr(y^*|x)} 
= \frac{\alpha(t,u)\beta(t,u)}{\sum_{t+u=t'+u'}\alpha(t',u')\beta(t',u')}
= \frac{\alpha_n(t,u)\beta_n(t,u)}{\sum_{t+u=t'+u'}\alpha_n(t',u')\beta_n(t',u')}
$

In [73]:
T,U=3,5
for i in range(U+T):

    for u in range ( max(0,i-T)):
        print(end="       ")

    for u in range ( max(0,i-T), min (i,U)):
        u=i-u-1

        print(str((u,u)).rjust(5),end=" ")
    print('\n')




(0, 0) 

(0, 1) (1, 0) 

(0, 2) (1, 1) (2, 0) 

       (1, 2) (2, 1) (3, 0) 

              (2, 2) (3, 1) (4, 0) 

                     (3, 2) (4, 1) 

                            (4, 2) 



In [76]:
import numpy as np

In [110]:

T,U=4,6

for i in range(U+T-1):
    offset= max(0,i-T+1)
    u=np.arange(offset,min(i+1,U))
    t=i-u
    print(str(t))
    print(str(u))


[0]
[0]
[1 0]
[0 1]
[2 1 0]
[0 1 2]
[3 2 1 0]
[0 1 2 3]
[3 2 1 0]
[1 2 3 4]
[3 2 1 0]
[2 3 4 5]
[3 2 1]
[3 4 5]
[3 2]
[4 5]
[3]
[5]


In [108]:
np.arange(10)[np.where(np.arange(10)<5)]

array([0, 1, 2, 3, 4])