In [106]:
from tinygrad.tensor import Tensor
from extra.utils import print_tree
# from temp.print_tree import print_tree
from tinygrad.nn.optim import Adam, LAMB
from tinygrad.nn import Linear

In [2]:
import functools
import itertools

In [3]:
import numpy as np
import librosa
import soundfile
import pathlib
import json
import matplotlib.pyplot as plt
from tinygrad.helpers import dtypes

In [127]:
from tinygrad.ops import Device

In [130]:
Device.DEFAULT = "CPU"

In [146]:
x, w = Tensor.normal(2,10),Tensor.normal(10,10)
(x[:1].dot(w) == x.dot(w)[:1]).numpy() # False

array([[0., 0., 0., 0., 1., 0., 0., 0., 1., 0.]], dtype=float32)

In [149]:
np.allclose(x[:1].dot(w).numpy(), x.dot(w)[:1].numpy())

True

In [147]:
(x[:1].dot(w) == x.dot(w)[:1]).numpy()

array([[0., 0., 0., 0., 1., 0., 0., 0., 1., 0.]], dtype=float32)

In [124]:
print_tree(Tensor.rand())

  0 ━┳ RESHAPE 
  1  ┗━━ RAND 1695929514


In [81]:
(x[:1].dot(w) - x.dot(w)[:1]).numpy()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)